// <auto-generated />
namespace prototype_four.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class justchecking : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(justchecking));
        
        string IMigrationMetadata.Id
        {
            get { return "202110040552130_justchecking"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
